dubbo:
  application:
    name: ${spring.application.name}
    protocol: tri
    serialize-check-status: DISABLE
  registry:
    address: zookeeper://${zookeeper.address:127.0.0.1}:2181
  protocol:
    name: tri
    port: -1
