version: "3.9"
services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    networks:
      - net_common
    ports:
      - "9999:9999"
    environment:
      TZ: Asia/Shanghai
      MONGO_SERVER: mongo
      REDIS_SERVER: redis-master
      APP_RUN_IN_HOST: "192.168.2.131"
      APP_RUN_IN_PORT: 9999
    volumes:
      - ..:/workspace:cached
      - $HOME/.m2:/root/.m2
      - $HOME/data:/root/data
    command: sleep infinity

networks:
  net_common:
    external: true
