version: '3'
services:
  spring-boot-case:
    image: F.LuVx/spring-boot-case:latest
    container_name: spring-boot-case
    build:
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    extra_hosts:
      - luvx:127.0.0.1
#    depends_on:
#      - nginx