server:
  port: 8090

spring:
  freemarker:
    template-loader-path: classpath:/templates
  mvc:
    static-path-pattern: /static/**
  thymeleaf:
    mode: HTML
  http:
    multipart:
      max-request-size: 200MB
      max-file-size: 20MB
