spring:
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
    timeout: 5000
#    lettuce:
#      pool:
#        enabled: true
#        max-active: 8 # ????? ??8 ?????????
#        max-wait: -1 # ???????????????????? ??-1
#        max-idle: 8 # ?????? ??8
#        min-idle: 0 # ?????? ??0
#  cache:
#    type: redis
#    redis:
#      use-key-prefix: true
#      key-prefix: luvx-
#      cache-null-values: false
