
### GET
GET http://127.0.0.1:8090/callable HTTP/1.1

### GET
GET http://127.0.0.1:8090/deferred HTTP/1.1

###
GET http://127.0.0.1:8090/webasync HTTP/1.1

###
GET http://127.0.0.1:8090/async HTTP/1.1

###
GET http://127.0.0.1:8090/async1 HTTP/1.1

###
