spring:
  data:
    mongodb:
      uri: mongodb+srv://xxx:xxx@cluster0.r8xxd.mongodb.net/boot
      auto-index-creation: true

logging:
  level:
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG
