server:
  port: 8090
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: 1121
    url: jdbc:mysql://luvx:53306/boot?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC&useSSL=false&allowMultiQueries=true
    username: root

logging:
  level:
    org.luvx:
        anno.mapper: debug
        mapper: debug
mybatis:
  type-aliases-package: org.luvx.entity
