###
POST http://localhost:8090/v2/createOrUpdate
content-type: application/json

{
    "id": "_2",
    "cron": "0/10 * * * * ?",
    "sql": "select * from user"
}

###

DELETE http://localhost:8090/v2/delete/_2

###
GET http://localhost:8090/v2/select

