spring:
  kafka:
    bootstrap-servers: mini.rx:19092,mini.rx:29092,mini.rx:39092
    template:
      default-topic: mars-topic
    producer:
      acks: 1 # 0-不应答。1-leader 应答。all-所有 leader 和 follower 应答。
      retries: 3
      # 每次批量发送消息的数量
      batch-size: 16384
      # 32M批处理缓冲区
      buffer-memory: 33554432
      properties:
        linger-ms: 1
      # 指定消息key和消息体的编解码方式
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      # 指定默认消费者group id
      group-id: consumer-group-mars
      auto-offset-reset: latest
      max-poll-records: 500
      fetch-max-wait: 10000
      # fetch-min-size: 1
      enable-auto-commit: true
      auto-commit-interval: 500
      # 指定消息key和消息体的编解码方式
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    listener:
      # listener容器中的线程数，用于提高并发量
      concurrency: 1
      # 轮询消费者时使用的超时（以毫秒为单位）
      poll-timeout: 50000
