spring:
  application:
    name: service-impl

server:
  http2:
    enabled: true

grpc:
  server:
    port: 9090
##    security:
##      enabled: true
##      certificateChain: file:certificates/server.crt
##      privateKey: file:certificates/server.key
