
### 创建

GET http://localhost:8080/expense/add?userId=123&money=123321

### 查看待办列表

GET http://localhost:8080/expense/list?userId=123

### 同意

GET http://localhost:8080/expense/apply?taskId=

### 拒绝

GET http://localhost:8080/expense/reject?taskId=

### 生成流程图

http://localhost:8080/expense/processDiagram?processId=
