### 创建

POST http://localhost:8080/flowable/inst/start?procDefId=&procDefKey={Expense}
Content-Type: application/json;charset=UTF-8

{
    "taskUser": "123",
    "money": 123321,
    "nums": [100,200,300,400]
}


### 列表

GET http://localhost:8080/flowable/inst/list?instanceId=&userId={boss}


### 图形

GET http://localhost:8080/flowable/inst/processDiagram?processId={}
