postfix: sso1

server:
  port: 8083
  servlet:
    session:
      cookie:
        name: ${postfix}

security:
  oauth2:
    client:
      client-id: client-${postfix}
      client-secret: 1121
      user-authorization-uri: http://localhost:8080/oauth/authorize
      access-token-uri: http://localhost:8080/oauth/token
    resource:
      user-info-uri: http://localhost:8081/user