spring:
  r2dbc:
    url: r2dbc:mysql://luvx:53306/boot?useUnicode=true&allowPublicKeyRetrieval=true&characterEncoding=utf-8&serverTimezone=UTC&useSSL=true&allowMultiQueries=true
    username: root
    password: 1121
    pool:
      enabled: true
      initial-size: 10
      max-size: 10

logging:
  level:
    org.springframework.data.r2dbc.core.R2dbcEntityTemplate: debug
    org.springframework.jdbc.core.JdbcTemplate: debug
