
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://luvx:53306/boot?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC&useSSL=false&allowMultiQueries=true
    username: root
    password: 1121

mybatis-plus:
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: org.luvx.entity
#  type-aliases-super-type: java.lang.Object
#  config-location: classpath:mybatis/mybatis-config.xml
#  mapper-locations: classpath:org/luvx/mapper/*.xml


logging:
  level:
    org:
      luvx:
        mapper: debug

