server:
  port: 9999

spring:
  boot:
    admin:
      client:
        url: http://localhost:${server.port}
        instance:
          service-base-url: http://localhost:${server.port}
  jmx:
    enabled: true
  profiles:
    include: base,tome,db,dubbo
  threads:
    virtual:
      enabled: true

swagger:
  enable: true

logging:
  level:
    root: info

api:
  baseUrl:
    github: https://gitee.com/api/v5/

management:
  endpoints:
    enabled-by-default: true
    web:
      base-path: /actuator
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
    shutdown:
      enabled: true
  info:
    env:
      enabled: true

app:
  switch:
    exception:
      handler:
        enable: true
