spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://luvx:53306/boot?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC&useSSL=true&allowMultiQueries=true
    username: root
    password: 1121

# 打印sql
logging:
  level:
    org.springframework.jdbc.core.JdbcTemplate: debug
