spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://luvx:53306/boot?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC&useSSL=true&allowMultiQueries=true
    username: root
    password: 1121
    hikari:
      max-lifetime: 600000
  data:
    mongodb:
      uri: mongodb+srv://xxx:xxx@cluster0.r8xxd.mongodb.net/boot
      # uri: mongodb://luvx:1121@${MONGO_SERVER:localhost}:27017/boot
    redis:
      url: redis://xxx:xxx@redis-16127.c294.ap-northeast-1-2.ec2.cloud.redislabs.com:16127
      # url: redis://xxx:xxx@${REDIS_SERVER:localhost}:6379

#  logging:
#    level:
#      org.luvx.boot.tools.dao.mapper: debug
#      org.springframework.data.mongodb.core.MongoTemplate: DEBUG

mybatis:
  mapper-locations: classpath:org/luvx/tools/dao/*/*.xml
  type-aliases-package: org.luvx.boot.tools.dao

debezium.source:
  serverId: 223344
  serverName: debezium_01
  hostname: luvx
  port: 53306
  user: root
  password: 1121
  databaseIncludeList: boot
  #  tableIncludeList: boot.user
  storageFile: /tmp/offsets.dat
  historyFile: /tmp/custom-file-db-history.dat
  flushInterval: 10000
