wechat:
  corpid: ww8d37a0aa1597c901
  corpsecret: HPLUBGQG1WOuZISxsKLyE34xFE9uPhcrYWIg3-tQSAk
  agentid: 1000003
  token: jKiBBwi0Jjtoi
  encodingAesKey: 4hIqXU7p2QiuLsNlvid7penWxzMSKs2eSXhzPxpHmGl
moji:
  appCode: efaf97d9328b4735bdba56f014035157
  token: 443847fa1ffd4e69d929807d42c2db1b