mybatis-plus:
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: org.luvx.fund.entity
#  type-aliases-super-type: java.lang.Object
#  config-location: classpath:mybatis/mybatis-config.xml
#  mapper-locations: classpath:org/luvx/mapper/*.xml

logging:
  level:
    org:
      luvx:
        fund:
          mapper: debug

nacos:
  config:
    bootstrap:
      enable: true
    server-addr: luvx:58848
    data-id: org.luvx.fund
    group: DEFAULT_GROUP
    type: yaml
    auto-refresh: true
    enable-remote-sync-config: true
    remote-first: true
    ext-config:
      - data-id: application-mybatis.yml
        group: DEFAULT_GROUP
        type: yaml
      - data-id: application-mail.yml
        group: DEFAULT_GROUP
        type: yaml
