
### 浏览器打开

GET http://localhost:8080/oauth/authorize?client_id=javayz&response_type=code

### 浏览器自动请求

POST http://localhost:8080/oauth/authorize?client_id=javayz&response_type=code

user_oauth_approval=true&scope.all=true&authorize=Authorize

### 浏览器自动请求

GET http://localhost:8080/callback?code=JbjX93
authorization: Bearer aT5_53s5akcU44pjHSSyxfiLZUI

### postman 请求

POST http://localhost:8080/oauth/token?code=JbjX93&grant_type=authorization_code&redirect_url=http://localhost:8080/callback&scope=all&client_id=javayz&client_secret=my_secret

### postman 请求

POST http://localhost:8080/oauth/check_token?token=aT5_53s5akcU44pjHSSyxfiLZUI

###

GET http://localhost:8080/
authorization: Bearer aT5_53s5akcU44pjHSSyxfiLZUI
