server:
  port: 8080

spring:
  application:
    name: auth-server
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://luvx:53306/security?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC&useSSL=false&allowMultiQueries=true
    username: root
    password: 1121
  main:
    allow-bean-definition-overriding: true
  # 使用redis存储 token
#  redis:
#    database: 2
#    host: localhost
#    port: 6379
#    password:
#    jedis:
#      pool:
#        max-active: 8
#        max-idle: 8
#        min-idle: 0
#    timeout: 100ms

management:
  endpoint:
    health:
      enabled: true
