#============== app ===================
server:
  port: 8090

#============== kafka ===================
# 指定kafka 代理地址，可以多个
spring:
  kafka:
    bootstrap-servers: localhost:59092
    producer:
      retries: 0
      # 每次批量发送消息的数量
      batch-size: 16384
      buffer-memory: 33554432
      # 指定消息key和消息体的编解码方式
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      # 指定默认消费者group id
      group-id: consumer-group-spring
      auto-offset-reset: earliest
      enable-auto-commit: true
      auto-commit-interval: 100
      # 指定消息key和消息体的编解码方式
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

kafka:
  topic:
    topic-name: topic-spring

#=============== log =======================
logging:
  level:
    org.apache.kafka: off