
###

GET http://127.0.0.1:8090/api/user/v2/xieren HTTP/1.1
content-type: application/json

{
    "name": "hahaha"
}

### 

GET http://127.0.0.1:8090/api/user/v3 HTTP/1.1
content-type: application/json

{
    "id": 19,
    "name": "hahaha"
}