### 增

POST http://luvx:8083/connectors HTTP/1.1
Content-type: application/json
Accept: application/json

{
  "name": "luvx-connector",
  "config": {
    "connector.class": "io.debezium.connector.mysql.MySqlConnector",
    "database.hostname": "127.0.0.1",
    "database.port": "3306",
    "database.user": "root",
    "database.password": "1121",
    "database.server.id": "1",
    "database.server.name": "luvx",
    "database.history.kafka.bootstrap.servers": "luvx:59092",
    "database.history.kafka.topic": "dbhistory.fullfillment",
    "include.schema.changes": "true"
  }
}

### 删

DELETE http://luvx:8083/connectors/luvx-connector HTTP/1.1

### 查1
GET http://luvx:8083/connectors HTTP/1.1

### 查2

GET http://luvx:8083/connectors/luvx-connector/config HTTP/1.1
