spring:
  application:
    name: dubbo-provider
# dubbo 相关配置(dubbo 的配置不再以 spring 开头)
dubbo:
  application:
    name: ${spring.application.name} # 应用名称
    protocol: tri
  registry:
    address: zookeeper://${zookeeper.address:127.0.0.1}:2181 # 注册中心信息
  protocol:
    name: tri # 协议名称
    port: -1 # 协议端口
#    serialization: protobuf
